#!/usr/bin/env bash
set -euo pipefail

NOTEBOOK="${1:-}"

if [[ $# -gt 1 ]]; then
    echo "Notebook name cannot contain spaces"
    echo "[Usage] $0 <notebook-name>"
    exit 1
fi

if [[ -z "$NOTEBOOK" ]]; then
    echo "[Usage] $0 <notebook-name>"
    exit 1
fi

CERN_USERNAME="${CERN_USERNAME:-}"

if [[ -z "$CERN_USERNAME" ]]; then
    CERN_USERNAME=$(
        klist 2>/dev/null \
        | grep -oE '[^[:space:]]+@CERN\.CH' \
        | sed 's/@CERN\.CH$//' \
        | head -n 1
    )

    if [[ -z "$CERN_USERNAME" ]]; then
        echo "Username is auto-detected through your Kerberos token."
        echo "Please run:"
        echo "  kinit yourusername@CERN.CH"
        echo
        echo "If Kerberos is not installed, set the environment variable CERN_USERNAME manually."
        exit 1
    fi
fi

EOS_HOME="/eos/user/${CERN_USERNAME:0:1}/${CERN_USERNAME}"
NB_PREFIX="/notebook/${CERN_USERNAME}/${NOTEBOOK}"

echo "Configuring notebook server with the following parameters"
echo "CERN username: $CERN_USERNAME"
echo "EOS home:      $EOS_HOME"
echo "Notebook URL:  $NB_PREFIX"
echo "Notebook:      $NOTEBOOK"
echo "---------------------------------------------------------"

IMAGE=$(
    kubectl get notebook "$NOTEBOOK" \
        -n "$CERN_USERNAME" \
        -o jsonpath='{.spec.template.spec.containers[0].image}'
) || {
    echo "ERROR: Could not get image for notebook $NOTEBOOK" >&2
    exit 1
}

if [[ "$IMAGE" != "ghcr.io/ekatralis/xsuite-containers:"* ]]; then
    echo "ERROR: Unsupported notebook image: $IMAGE" >&2
    echo "Ensure that the notebook is using an image from: ghcr.io/ekatralis/xsuite-containers:<tag>" >&2
    exit 1
fi

echo "Detected notebook with image: $IMAGE"

kubectl patch notebook "$NOTEBOOK" \
    -n "$CERN_USERNAME" \
    --type=json \
    -p="[
        {
            \"op\": \"add\",
            \"path\": \"/spec/template/spec/securityContext\",
            \"value\": {
                \"fsGroup\" : 100,
                \"supplementalGroups\": [2020]
            }
        },
        {
            \"op\": \"add\",
            \"path\": \"/spec/template/spec/containers/0/args\",
            \"value\": [
                \"lab\",
                \"--notebook-dir=${EOS_HOME}\",
                \"--ip=0.0.0.0\",
                \"--no-browser\",
                \"--port=8888\",
                \"--ServerApp.token=\",
                \"--ServerApp.password=\",
                \"--ServerApp.allow_origin=*\",
                \"--ServerApp.allow_remote_access=True\",
                \"--ServerApp.authenticate_prometheus=False\",
                \"--ServerApp.base_url=${NB_PREFIX}\",
                \"--ServerApp.websocket_ping_timeout=0\",
                \"--ServerApp.websocket_ping_interval=0\"
            ]
        },
        {
            \"op\": \"add\",
            \"path\": \"/spec/template/spec/containers/0/command\",
            \"value\": [\"jupyter\"]
        },
        {
            \"op\": \"add\",
            \"path\": \"/spec/template/spec/containers/0/env\",
            \"value\": [
                {
                    \"name\": \"PYTHONUSERSITE\",
                    \"value\": \"0\"
                },
                {
                    \"name\": \"PYTHONNOUSERSITE\",
                    \"value\": \"1\"
                }
            ]
        }

    ]"

echo "Waiting for Notebook controller to update StatefulSet..."

for i in $(seq 1 30); do
    COMMAND=$(
        kubectl get sts "$NOTEBOOK" \
            -n "$CERN_USERNAME" \
            -o jsonpath='{.spec.template.spec.containers[0].command[0]}' \
            2>/dev/null || true
    )

    if [ "$COMMAND" = "jupyter" ]; then
        break
    fi

    sleep 2
done

if [ "$COMMAND" != "jupyter" ]; then
    echo "ERROR: StatefulSet was not updated with command=jupyter"
    exit 1
fi

echo "Restarting notebook pod..."

kubectl delete pod \
    -n "$CERN_USERNAME" \
    -l notebook-name="$NOTEBOOK" \
    --wait=true

echo "Waiting for replacement pod..."

POD=""

for i in $(seq 1 60); do
    POD=$(
        kubectl get pod \
            -n "$CERN_USERNAME" \
            -l notebook-name="$NOTEBOOK" \
            -o jsonpath='{.items[0].metadata.name}' \
            2>/dev/null || true
    )

    if [ -n "$POD" ]; then
        break
    fi

    sleep 1
done

if [ -z "$POD" ]; then
    echo "ERROR: Replacement notebook pod was not created"
    exit 1
fi

echo "Waiting for $POD to become Ready..."

kubectl wait \
    --for=condition=Ready \
    "pod/$POD" \
    -n "$CERN_USERNAME" \
    --timeout=300s

echo "Notebook is ready."
echo "Try accessing via:"
echo " 	ssh ${NOTEBOOK}@accpoc.cern.ch" 
echo "or via the UI at:"
echo "	https://accpoc.cern.ch/notebook/${CERN_USERNAME}/${NOTEBOOK}/lab?"
