universe                = docker
docker_image            = registry.cern.ch/ghcr.io/ekatralis/xsuite-slim:latest
executable              = print_info.sh
arguments               = ""
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
output                  = out.$(ClusterId).$(ProcId)
error                   = err.$(ClusterId).$(ProcId)
log                     = log.$(ClusterId)
request_memory          = 1G
queue 1